spring.application.name=notification-service
server.port=9040

# --- Database & Eureka ---
spring.datasource.url=jdbc:postgresql://localhost:5432/notification
spring.datasource.username=postgres
spring.datasource.password=Rahul@123
spring.jpa.hibernate.ddl-auto=update
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# --- Kafka (Nuclear Wake-Up Config) ---
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-service-v6
spring.kafka.consumer.auto-offset-reset=earliest

# VERY IMPORTANT: This MUST be StringDeserializer, not LongDeserializer!
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.LongDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# --- Debug Logs ---
logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=INFO