spring.application.name=user-service

server.servlet.context-path=/users
jwt.secretKey=jhdshcbsdbchsbdcewifwfnnrlgkeofnsdknskefwejfhwbgvvghftr6465456tcfcvnkjnjbjhbutyr65edrfvlmnjbhvjcgcfxcytfyt65e5e5d5ftgy8gf5d4duh774w3w433thjghcfxserswegvjggyut4wcghf
server.port = 9020

spring.datasource.url=jdbc:postgresql://user-db:5432/dbuser
spring.datasource.username=postgres
spring.datasource.password=Rahul@123
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone= http://discovery-server:8761/eureka