spring.application.name=connection-service

server.servlet.context-path=/connections
server.port=9030

spring.neo4j.uri=bolt://connection-db:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=Rahul@123

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
