spring.application.name=notification-service

server.port = 9040
spring.datasource.url=jdbc:postgresql://notification-db:5432/notification
spring.datasource.username=postgres
spring.datasource.password=Rahul@123
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone= http://discovery-server:8761/eureka